### PR TITLE
Add ability to publish content (closes #9)

### LINKED ISSUE #9: Need ability to publishing content (not just save)
Hi,

I'm testing UmbracoRestApi 0.9.0 together with Umbraco 7.3.1 and after some configuration i'm able to update a document i see the change in the backend, but the page is not updated. This seems to be related to the xml cache file which still had the old values in it. Do i need to make a publish call after the update (put) request?

### PR DESCRIPTION
**Pull request by mcliment**
It's a very simple implementation but works at least to publish content nodes via API as requested in #9

### CODE REVIEW

**Comment by Shazwazza** [comment]
Nice! Any chance you can get a test written for this? There's pretty much tests for all actions in the test proj

**Comment by mcliment** [comment]
I'll take a look to that test!

**Comment by mcliment** [comment]
I've added a test but there's not much to test because the JSON does not contain information on wether the content is published or not. Any suggested improvement?

**Comment by chrisross10** [comment]
Hey guys, just ran into this, any chance of getting it merged? C

**Comment by Shazwazza** [comment]
Sorry for the delay! Good news, we'll be pulling this project into the core, reviewing existing PRs, issues, etc... within the coming weeks, we'l reply when we start reviewing. 
Thanks for your patience!

**Comment by Shazwazza** [comment]
merging this in and i'll review and test, thanks for the effort! This project is getting the love it deserves now :)

**Pull request merged**
